### ISSUE TITLE
How to make application blur

### ISSUE THREAD

**Issue by 404cn** [ibhagwan/picom#2]
I just installed this picom and copy default config file to my $HOME/.config/

And add `"class_g = 'Emacs'"` to `blur-background-exclude`.

But it seems not work.

**Comment by ibhagwan** [comment]
Your title asks how to enable blur but you're asking about configuring `blur-background-exclude` which is used to actually exclude an application from being blurred.

First make sure you're using the correct `class` for your application, to find out the right one you can use `xprop` and then use the mouse to click on the right window and look for the line with `WM_CLASS(STRING)`, it should look something like this:
```
WM_CLASS(STRING) = "Navigator", "Firefox"
```

Note that you have to use the last part of the output (in our case "Firefox") for the right class.

Note that this alone won't enable blur, I am assuming you're using this fork because you'd like to use the `dual_kawase` blur option, to do so make sure the following configuration options are set.
```
experimental-backends = true;
backend = "glx";
blur: {
  method = "dual_kawase";
  strength = 7;
}
```

Play around with `experimental-backends = false;` and the `strength = {number};` option to your liking until you're happy with the result.

**Comment by 404cn** [comment]
> Your title asks how to enable blur but you're asking about configuring `blur-background-exclude` which is used to actually exclude an application from being blurred.
> 
> First make sure you're using the correct `class` for your application, to find out the right one you can use `xprop` and then use the mouse to click on the right window and look for the line with `WM_CLASS(STRING)`, it should look something like this:
> 
> ```
> WM_CLASS(STRING) = "Navigator", "Firefox"
> ```
> 
> Note that you have to use the last part of the output (in our case "Firefox") for the right class.
> 
> Note that this alone won't enable blur, I am assuming you're using this fork because you'd like to use the `dual_kawase` blur option, to do so make sure the following configuration options are set.
> 
> ```
> experimental-backends = true;
> backend = "glx";
> blur: {
>   method = "dual_kawase";
>   strength = 7;
> }
> ```
> 
> Play around with `experimental-backends = false;` and the `strength = {number};` option to your liking until you're happy with the result.

OH MY. Thanks for your detailed answer.

**Comment by ibhagwan** [comment]
I apologize for the delay, turns out this fork had issues closed for a long time, I opened it recently and I didn't know I had to "watch" the repository to get notifications, GitHub noob issues :)
