### ISSUE TITLE
Round corners for every window

### ISSUE THREAD

**Issue by scrouthtv** [ibhagwan/picom#26]
Hey, it's me again. Thanks for your help at #15 I now have rounded corners on my terminal:
![image](https://user-images.githubusercontent.com/23227405/107497339-bb7f2000-6b92-11eb-9995-cc6042a4b960.png)

Because of
```
round-borders-rule = [
	"2:class_g = 'Termite'"
];
```
the termite window has rounded corners.
Is there any way to have this apply to all windows? Or do I have to add this for every application?

Let's take this even one step further. [i3 has an option to only show borders on the windows if there is more than one window in the current workspace.](https://i3wm.org/docs/userguide.html#_hiding_vertical_borders) Is there any way to only round the corners if they exist, e. g. only if there are multiple windows on the current workspace?

Thanks in advance

**Comment by ibhagwan** [comment]
There are many different ways to use the window property configuration options, this isn’t a code I added but rather part of the options that already exist in picom as part of the config parses. For example to exclude rounded corners from all “normal” windows, you can add `window_type = 'normal'` to `rounded-corners-exclude`.

I’m not sure if the below would work as I simply copied the code that parses the `opacity-rule` but there is a chance `5:window_type = 'normal'` might work as a generic rule, if you need other window types, below is from the sample `picom.conf`:

```
# 'WINDOW_TYPE' is one of the 15 window types defined in EWMH standard:
#     "unknown", "desktop", "dock", "toolbar", "menu", "utility",
#     "splash", "dialog", "normal", "dropdown_menu", "popup_menu",
#     "tooltip", "notification", "combo", and "dnd".
```

There are also more options than just window type, read the documentation to understand what’s possible and what isn’t.

Another option that might help here is the use of wildcard with `class_g`, I.e. `class_g *?= 'rofi'"`

> Let's take this even one step further. i3 has an option to only show borders on the windows if there is more than one window in the current workspace. Is there any way to only round the corners if they exist, e. g. only if there are multiple windows on the current workspace?

Technically this should happen, picom shouldn’t round the corners of a full screen window unless again i3 behaves differently here and the properties that tell picom the window is full screen show otherwise.

Talking more specifically about settings that are dependent based on number of visible windows, those aren’t possible AFAIK.
