### ISSUE TITLE
KDE Desktop Effects not working

### ISSUE THREAD

**Issue by IgnisFlamme** [ibhagwan/picom#9]
### Platform

Manjaro KDE 20.0.3

### Environment

KDE
### picom version

vgit-44b49
### Configuration:
```
## Corners
corner-radius = 15.0;

## Shadow
shadow = false;
shadow-radius = 20;
shadow-offset-x = -17;
shadow-offset-y = -7;
shadow-opacity = 0.5;
# shadow-exclude = [ "class_g = 'Polybar'"];

## other
detect-rounded-corners = true;

## fading
fading = true;
fade-delta = 0.25;
fade-in-step = 0.02;
fade-out-step = 0.02;
fade-exclude = [
];
no-fading-openclose=false

vsync=true

##General Settings
experimental-backends=true;
backend="glx"
```

### Expected behavior
KDE Desktop Effects work properly
### Current Behavior
None of the KDE Desktop Effects work.

**Comment by ibhagwan** [comment]
Hi,

I’m not even sure picom in general is supposed to work with KDE, I’ve never used KDE but my general understanding is that KDE has kwin as its compositor and perhaps it can’t co-exist with picom?
I haven’t single a single post on `/r/unixporn` using picom (with or without rounded corners or blur...), not sure if it’s because it isn’t working or simply because kwin provides most of the functionality making picom+KDE redundant.

Thanks foe the report nonetheless.

**Comment by SkyyySi** [comment]
KWin has a more powerful compositor build in, which also powers the desktop effects. KWin allows for extensions ("KWin scripts"), but picom does not (and why should it?). You cannot have 2 compositors at the same time. If you use KWin, don't bother with picom and just use the build in compositor. This is not an issue with picom.
